
# Task name - used to pick the class to load
task_name: ${task.name}
# experiment name. defaults to name of training config
experiment: ''

# if set to positive integer, overrides the default number of environments
num_envs: ''

# seed - set to -1 to choose random seed
seed: -1
# set to True for deterministic performance
torch_deterministic: False

# set the maximum number of learning iterations to train for. overrides default per-environment setting
max_iterations: ''

## Device config
physics_engine: 'physx'
# whether to use cpu or gpu pipeline
pipeline: 'gpu'
# whether to use cpu or gpu physx
sim_device: 'gpu'
# used for gpu simulation only - device id for running sim and task if pipeline=gpu
device_id: 0
# device to run RL
rl_device: 'cuda:0'
# multi-GPU training
multi_gpu: False

## PhysX arguments
num_threads: 4 # Number of worker threads used by PhysX - for CPU PhysX only.
solver_type: 1 # 0: pgs, 1: tgs

# RLGames Arguments
# test - if set, run policy in inference mode (requires setting checkpoint to load)
test: False
# used to set checkpoint path
checkpoint: ''
# evaluate checkpoint
evaluation: False

# disables rendering
headless: True  # <----------------------------------
# enables native livestream
enable_livestream: False
# timeout for MT script
mt_timeout: 300

# enables viewport recording
enable_recording: False
# interval between video recordings (in steps)
recording_interval: 2000
# length of the recorded video (in steps)
recording_length: 100
# fps for writing recorded video
recording_fps: 30
# directory to save recordings in
recording_dir: ''

wandb_activate: False
wandb_group: 'max_mod_fl2f_imu+FC_randF'
wandb_name: ${train.params.config.name}
wandb_entity: ''
wandb_project: 'my-awesome-Ant_ES_RBFHebb'

# path to a kit app file
kit_app: ''

# Warp
warp: False

# set default task and default training config based on task
defaults:
  - _self_
  - task: Dbalpha
  - train: ${task}PPO
  - override hydra/job_logging: disabled

# set the directory where the output files get saved
hydra:
  output_subdir: null
  run:
    dir: .

# Training params
EPOCHS: 100           # <----------------------------------
SAVE_EVERY: 100        # <----------------------------------
EPISODE_LENGTH_TRAIN: 500   # <----------------------------------
EPISODE_LENGTH_TEST: 500   # <----------------------------------
resume_train: False

custom_rewards: False

# ES algorithm Standard
ES_params:
  # POPSIZE: 1024 # workstation (500)
  rank_fitness: True
  antithetic: True
  learning_rate: 0.1 # 0.05:RBF
  learning_rate_decay: 0.995 # 0.9999
  sigma_init: 0.1 # 0.1
  sigma_decay: 0.999
  learning_rate_limit: 0.001
  sigma_limit: 0.0001

# model 
model: 'rbf' # rbf, rbf_ff, rbf_hebb, rbf_lstm
model_type: 'parallel_Hebb'
FF_ARCHITECTURE: [15, 40, 20, 8] # [num_input, num_hidd, num_output] dbAlpha 1 output
HEBB_ARCHITECTURE: [15, 20, 10, 8] # [num_input, num_hidd, num_output] dbAlpha 1 output
LSTM_ARCHITECTURE: [15, 30, 8] # [num_input, num_hidd, num_output] dbAlpha 1 output
HEBB_init_wnoise: 0.01
HEBB_norm: 'max'
RBF_ARCHITECTURE: [20, 18] # [num_kernel, num_output] dbAlpha 1 output
USE_TRAIN_RBF: False
USE_TRAIN_HEBB: False
USE_TRAIN_PARAM: False

# # Test params rbf_hebb network
# train_ff_path: 'Ant_test_rbf_ff_1628_99_132.3918.pickle' # flat terrain
# train_rbf_path: 'Ant_80_199_139.4822.pickle' # flat terrain
# train_hebb_path: 'Ant_test_rbf_hebb_2938_99_129.1072.pickle' # maxnorm
# # train_hebb_path: 'Ant_test_rbf_hebb_7868_99_128.0409.pickle'  # max large
# # train_hebb_path: 'Ant_test_rbf_hebb_2938_99_123.4924.pickle'  # flat terrain, clamp
# train_lstm_path: 'Ant_test_rbf_lstm_5880_99_131.3515.pickle'  # flat terrain, clamp
# # train_hebb_path: 'Ant_test_rbf_hebb_17600_299_55.65674.pickle'  # flat terrain
# # train_rbf_path: 'Ant_test_rbf_80_299_117.0807.pickle' # rough terrain
# # train_hebb_path: '.5065.pickle'  # flat terrain
collect_w_matrix: False

# Dbalpha trained weight
train_ff_path: 'Ant_test_rbf_ff_1628_99_132.3918.pickle' # flat terrain
train_rbf_path: 'Dbalpha_rbf_180_99_-0.28894.pickle' # flat terrain
train_hebb_path: 'Ant_test_rbf_hebb_2938_99_129.1072.pickle' # maxnorm
train_lstm_path: 'Ant_test_rbf_lstm_5880_99_131.3515.pickle'  # flat terrain, clamp


# Custom Terrain
terrain:
  staticFriction: 1.0  # [-]
  dynamicFriction: 1.0  # [-]
  restitution: 0.        # [-]
  # rough terrain only:
  curriculum: true
  maxInitMapLevel: 0
  mapLength: 15.
  mapWidth: 15.
  numLevels: 1 # x-axis
  numTerrains: 1 # 20, y-axis
  # terrain types: [smooth slope, rough slope, stairs up, stairs down, discrete]
  terrainProportions: [0.02, 0.9, 0.02, 0.02, 0.02]
  # tri mesh only:
  slopeTreshold: 0.5
  type: 'flat' #rough, slope
  slope_angle: 0.4
randomization:
  forces: [0.0, 0.0] #<-------- 